---
title: "Lab 02 - Global plastic waste"
author: "Team Name: Hamish, Matt, Herman, Rudy, Maya and Abdul"
date: "`r Sys.Date()`"
output: html_document
---

### Load packages and data

```{r load-packages, message = FALSE, warning=FALSE}
library(tidyverse)
library(readxl)
```


## Load & join data sets

```{r load-data, message = FALSE}
data1 <- read_csv("data/mismanaged-plastic-waste-per-capita.csv")



data2 <- read_csv2("data/per-capita-ocean-plastic-waste.txt")



data3 <- read_tsv("data/UN_country_population.tsv")



data4 <- read_excel("data/UN_country_region.xlsx")



```



```{r join-data, message = FALSE}
plastic_data_all <- data1




plastic_data_all <- data2 %>% 
  select(-name) %>% 
  left_join(plastic_data_all, by = "code")




plastic_data_all <- data3 %>%
  select(-name) %>%
  right_join(plastic_data_all, by = "code")




plastic_data_all <- data4 %>%
  select(-name) %>%
  right_join(plastic_data_all, by = "code")



```


```{r print-data, message = FALSE}
plastic_data_all %>% head(n = 10)



```



## Exercises

### Ex 1.

```{r Ex1, message = FALSE}
plastic_data_all %>%
  group_by(region) %>%
  count() %>%
  rename(frequency = n) %>%
  arrange(desc(frequency))

```
Africa has the most coastal regions.


### Ex 2.

```{r Ex2, message = FALSE}
plastic_data_all <- mutate(plastic_data_all, total_mismanaged_plastic = mismanaged_plastic * population) %>%
  group_by(region) %>% 
  summarise(mean_per_region=mean(total_mismanaged_plastic)) %>% 
  arrange(desc(mean_per_region))
  
```

Asia is the highest.
### Ex 3.

```{r Ex3, message = FALSE}
# Write your code here to answer exercise 3
#plastic_data_all <- plastic_data_all %>% 
 # mutate(pct_mismanaged_plastic_ocean = (mismanaged_plastic_ocean / mismanaged_plastic))


```


### Ex 4.

```{r Ex4, message = FALSE}
# Write your code here to answer exercise 4



```
